# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b191aad83261cba8d657623633f62d423f0e0bcc7647e1b35721764bba5907fc410053a8a15ca399fd88c0263f96acee0fc77ae4b45c701e567eb67a8599df72

test:
  secret_key_base: bea42decf5703b321b3e997f706d5b1ee9a04bc9c279fea400ee2088158fd97c6a991be1742fbfced855006ca65ca5df38eda777878ca6959ff77ee95a56085f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
